// src/lib/components/ScrollProgress.svelte
<div
	class="pointer-events-none fixed inset-y-0 left-2 z-40 hidden w-0.5 bg-cream-lighter motion-safe:supports-[animation-timeline:scroll(root_block)]:block lg:left-6"
	aria-hidden="true"
>
	<span
		class="block size-full origin-top [transform:scaleY(0)] bg-gold supports-[animation-timeline:scroll(root_block)]:animate-scroll-progress supports-[animation-timeline:scroll(root_block)]:[animation-duration:auto] supports-[animation-timeline:scroll(root_block)]:[animation-timeline:scroll(root_block)]"
	></span>
</div>

// src/components/motion/ScrollProgress.tsx
'use client'

import { motion, useScroll, useSpring } from 'motion/react'

export function ScrollProgress() {
  const { scrollYProgress } = useScroll()
  const scaleY = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  })

  return (
    <motion.div
      className="fixed left-2 lg:left-6 top-0 bottom-0 w-[2px] bg-cream-lighter origin-top z-40"
      style={{ scaleY }}
    >
      <motion.div className="absolute inset-0 bg-gold" style={{ scaleY }} />
    </motion.div>
  )
}
