// src/components/ui/Timeline.tsx
'use client'

import { ScrollReveal } from '@/components/motion/ScrollReveal'

export interface TimelineItemData {
  id: number | string
  title: string
  subtitle: string
  startDate: string
  endDate?: string | null
  description?: string
}

interface TimelineProps {
  items: TimelineItemData[]
  header?: {
    label: string
    count?: number
  }
  showTopBorder?: boolean
}

function formatDate(dateString: string | null | undefined) {
  if (!dateString) return 'Present'
  return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric' })
}

export function Timeline({ items, header, showTopBorder = false }: TimelineProps) {
  if (!items || items.length === 0) return null

  return (
    <section
      className={`py-24 lg:py-32 pl-8 pr-6 lg:px-12 bg-charcoal text-cream ${showTopBorder ? 'border-t border-border' : ''}`}
    >
      <div className="max-w-6xl mx-auto">
        {header && (
          <header className="flex items-baseline justify-between mb-16">
            <h2 className="font-serif text-4xl lg:text-5xl tracking-tight">{header.label}</h2>
            <span className="font-sans text-xs uppercase tracking-[0.2em] text-stone">
              {header.count} item{header.count !== 1 ? 's' : ''}
            </span>
          </header>
        )}

        <div className="relative">
          <div className="absolute left-[19px] top-2 bottom-2 w-[1px] bg-border" />

          <div className="space-y-16">
            {items.map((item, index) => (
              <ScrollReveal key={item.id} delay={index * 0.1}>
                <div className="relative pl-12">
                  <div className="absolute left-[-5px] top-[7px] w-[3px] h-[3px] bg-stone rounded-full" />

                  <div className="mb-2">
                    <span className="font-sans text-xs uppercase tracking-[0.2em] text-stone">
                      {formatDate(item.startDate)} — {formatDate(item.endDate)}
                    </span>
                  </div>

                  <h3 className="font-serif text-xl lg:text-2xl mb-1">{item.title}</h3>

                  <p className="font-sans text-base text-gold mb-3">{item.subtitle}</p>

                  {item.description && (
                    <p className="font-sans text-stone-light leading-relaxed text-pretty">
                      {item.description}
                    </p>
                  )}
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

// src/lib/components/Timeline.svelte
<script lang="ts">
	import Reveal from './Reveal.svelte';
	import SectionHeader from './SectionHeader.svelte';

	type TimelineItem = {
		slug: string;
		title: string;
		subtitle: string;
		startDate: string;
		endDate?: string;
		isCurrent?: boolean;
		html?: string;
	};

	let {
		title,
		items,
		topBorder = false
	}: { title: string; items: TimelineItem[]; topBorder?: boolean } = $props();

	function year(date?: string) {
		return date ? new Date(`${date}T00:00:00.000Z`).getUTCFullYear() : 'Present';
	}

	let headingId = $derived(`${title.toLowerCase().replaceAll(' ', '-')}-title`);
</script>

<section
	class={['timeline-section', topBorder && 'timeline-section--border']}
	aria-labelledby={headingId}
>
	<div class="section-container">
		<Reveal>
			<SectionHeader
				{title}
				id={headingId}
				meta={`${items.length} ${items.length === 1 ? 'item' : 'items'}`}
			/>
		</Reveal>

		<div class="timeline-list">
			{#each items as item, index (item.slug)}
				<Reveal delay={index * 90}>
					<article>
						<span class="marker" aria-hidden="true"></span>
						<p class="date">
							{year(item.startDate)} - {item.isCurrent ? 'Present' : year(item.endDate)}
						</p>
						<h3>{item.title}</h3>
						<p class="subtitle">{item.subtitle}</p>
						{#if item.html}
							<div class="description">{@html item.html}</div>
						{/if}
					</article>
				</Reveal>
			{/each}
		</div>
	</div>
</section>

<style>
	.timeline-section {
		background: var(--color-charcoal);
		color: var(--color-cream);
		padding: var(--section-space) var(--page-gutter);
	}

	.timeline-section--border {
		border-top: 1px solid var(--color-border);
	}

	.section-container {
		width: min(100%, var(--content-width));
		margin-inline: auto;
	}

	.timeline-list {
		position: relative;
		display: grid;
		gap: 4rem;
		border-left: 1px solid var(--color-border);
		padding-inline-start: 3rem;
	}

	article {
		position: relative;
	}

	.marker {
		position: absolute;
		top: 0.5rem;
		left: calc(-3rem - 2px);
		width: 3px;
		height: 3px;
		background: var(--color-stone);
	}

	.date {
		margin: 0 0 0.5rem;
		color: var(--color-stone);
		font-size: 0.75rem;
		font-weight: 500;
		text-transform: uppercase;
	}

	h3 {
		margin: 0 0 0.25rem;
		font-family: var(--font-serif);
		font-size: 1.75rem;
		font-weight: 400;
		line-height: 1.15;
	}

	.subtitle {
		margin: 0;
		color: var(--color-gold);
	}

	.description :global(p) {
		max-width: 44rem;
		margin: 0.75rem 0 0;
		color: var(--color-stone-light);
		line-height: 1.7;
	}

	@media (min-width: 64rem) {
		h3 {
			font-size: 2rem;
		}
	}
</style>
