// src/lib/components/ProjectCard.svelte
<script lang="ts">
	import { reveal } from '$lib/actions/reveal';
	import type { Project } from '$lib/data/portfolio';
	let { project }: { project: Project } = $props();
</script>

{#snippet heading(technical = false)}
	<span
		class={[
			'mb-3 block text-xs leading-normal tracking-[0.2em] uppercase',
			project.accent === 'sage' ? 'text-sage-on-cream' : 'text-gold-on-cream'
		]}>{project.category}</span
	>
	<h3
		class={[
			'font-serif leading-[1.2] font-normal',
			technical ? 'text-3xl' : 'mb-3 text-2xl lg:text-3xl'
		]}
	>
		{project.title}
	</h3>
{/snippet}

<article
	use:reveal
	class={[
		'group/project grid grid-cols-1 items-start gap-6 lg:grid-cols-12 lg:gap-8',
		project.image
			? 'transition-[translate,box-shadow] duration-300 ease-out motion-reduce:transition-none [@media(hover:hover)_and_(pointer:fine)]:hover:-translate-y-1 [@media(hover:hover)_and_(pointer:fine)]:hover:shadow-[0_10px_15px_-3px_rgb(0_0_0/8%)]'
			: 'border-t border-cream-lighter pt-8'
	]}
>
	<!-- eslint-disable svelte/no-navigation-without-resolve -- Project URLs are external destinations. -->
	{#if project.image}
		<a
			class={[
				'flex aspect-video min-w-0 items-center justify-center overflow-hidden text-center font-serif text-lg text-stone-light shadow-[0_0_0_1px_rgb(0_0_0/8%)] lg:col-span-7',
				project.accent === 'sage' ? 'bg-cream-light' : 'bg-cream-lighter'
			]}
			href={project.url}
			aria-label={`Visit ${project.title}`}
		>
			<img
				class={[
					'h-full w-full object-top transition-transform duration-400 motion-reduce:transition-none [@media(hover:hover)_and_(pointer:fine)]:group-hover/project:scale-[1.025]',
					project.imageFit === 'logo' ? 'bg-[#dadada] object-contain p-6' : 'object-cover'
				]}
				src={project.image}
				alt={project.alt}
				width="1440"
				height="960"
				loading="lazy"
			/>
		</a>
	{:else}
		<div class="lg:col-span-5">{@render heading(true)}</div>
	{/if}
	<div class={project.image ? 'lg:col-span-5 lg:pt-4' : 'lg:col-span-7'}>
		{#if project.image}{@render heading()}{/if}
		<p class="mb-4 leading-[1.625] text-slate">{project.description}</p>
		<ul class="mb-4 flex list-none flex-wrap gap-2 p-0">
			{#each project.technologies as technology (technology)}<li
					class="bg-cream-lighter px-2 py-1 text-xs leading-4 text-slate"
				>
					{technology}
				</li>{/each}
		</ul>
		{#if project.url}
			<a
				class="group/link inline-flex items-center gap-1.5 text-sm leading-normal"
				href={project.url}
				><span
					class="relative after:absolute after:right-0 after:-bottom-[3px] after:left-0 after:h-px after:origin-left after:scale-x-0 after:bg-current after:transition-transform after:duration-300 after:ease-[cubic-bezier(0.25,0.46,0.45,0.94)] group-focus-visible/link:after:scale-x-100 motion-reduce:after:transition-none [@media(hover:hover)_and_(pointer:fine)]:group-hover/link:after:scale-x-100"
					>Visit site</span
				> <span aria-hidden="true">↗</span></a
			>
		{/if}
	</div>
	<!-- eslint-enable svelte/no-navigation-without-resolve -->
</article>

// src/components/ui/ProjectCard.tsx
'use client'

import { ArrowSquareOut } from '@phosphor-icons/react'
import { StaggerContainer, StaggerItem } from '@/components/motion/StaggerContainer'

interface ProjectCardProps {
  project: {
    id: number
    title: string
    excerpt: string
    description?: any
    featuredImage: any
    technologies?: any[]
    context?: string
    company?: string
    liveUrl?: string | null
  }
}

function AnimatedUnderline({ children }: { children: React.ReactNode }) {
  return (
    <span className="relative inline-block group">
      <span className="relative">
        {children}
        <span className="absolute bottom-0 left-0 w-full h-[1px] bg-current origin-left scale-x-0 group-hover:scale-x-100 transition-transform duration-300" />
      </span>
    </span>
  )
}

function ImageLift({
  children,
  className = '',
}: {
  children: React.ReactNode
  className?: string
}) {
  return (
    <div className={`relative overflow-hidden ${className} group`}>
      <div className="h-full w-full transition-transform duration-400 lg:group-hover:scale-102">
        {children}
      </div>
    </div>
  )
}

export function ProjectCard({ project }: ProjectCardProps) {
  const featuredBg = project.context === 'work' ? 'bg-cream-lighter' : 'bg-cream-light'
  const categoryColor = project.context === 'work' ? 'text-gold' : 'text-sage'
  const categoryLabel =
    project.context === 'work'
      ? `Client Work at ${project.company || 'Company'}`
      : project.context === 'personal'
        ? 'Personal Project'
        : 'Project'

  const imageUrl =
    typeof project.featuredImage === 'object' && project.featuredImage !== null
      ? project.featuredImage.url
      : null

  return (
    <article className="group lg:hover:-translate-y-1 lg:hover:shadow-lg max-lg:active:scale-[0.98] transition-all duration-300 ease-out">
      <a href={project.liveUrl || '#'} target="_blank" rel="noopener noreferrer" className="block">
        <StaggerContainer className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start">
          <StaggerItem className="lg:col-span-7">
            <ImageLift className={`${featuredBg} ring-1 ring-black/[0.08]`}>
              {imageUrl ? (
                <img
                  src={imageUrl}
                  alt={
                    typeof project.featuredImage === 'object' &&
                    project.featuredImage !== null &&
                    project.featuredImage.alt
                      ? project.featuredImage.alt
                      : project.title
                  }
                  className="h-auto w-full"
                />
              ) : (
                <div className="aspect-video flex items-center justify-center text-stone-light font-serif text-lg">
                  {project.title}
                </div>
              )}
            </ImageLift>
          </StaggerItem>
          <StaggerItem className="lg:col-span-5 lg:pt-4">
            <span
              className={`font-sans text-xs uppercase tracking-[0.2em] ${categoryColor} mb-3 block`}
            >
              {categoryLabel}
            </span>
            <h3 className="font-serif text-2xl lg:text-3xl mb-3">{project.title}</h3>
            <p className="font-sans text-slate mb-4 leading-relaxed">{project.excerpt}</p>
            {project.technologies && project.technologies.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-4">
                {project.technologies.map((tech: any) => (
                  <span
                    key={tech.id}
                    className="font-sans text-xs px-2 py-1 bg-cream-lighter text-slate"
                  >
                    {typeof tech === 'string' ? tech : tech.name}
                  </span>
                ))}
              </div>
            )}
            <span className="inline-flex items-center gap-1 font-sans text-sm text-charcoal group-hover:gap-2 transition-all">
              <AnimatedUnderline>Visit site</AnimatedUnderline>
              <ArrowSquareOut size={14} />
            </span>
          </StaggerItem>
        </StaggerContainer>
      </a>
    </article>
  )
}
